django_projects/batch/batch/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.views.generic import TemplateView



urlpatterns = [
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('admin/', admin.site.urls),
    path('unesco/', include('unesco.urls')),
    path('unesco_more/', include('unesco_more.urls')),
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep
]


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

django_projects/batch/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view()),
]

django_projects/batch/unesco/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='unesco'
urlpatterns = [
    path('', views.RegionView.as_view(), name='all'),
    # path('site/<int:site_id>', views.SiteView.as_view(), name='site_list'),
    # path('site_list/<int:pk>', views.getsite, name='site_list'),
    path('site/<int:region_id>', views.SiteDetailView.as_view(), name='site_list'),
    # path('ad/creat
    #     views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    # path('ad/<int:pk>/update',
    #     views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    # path('ad/<int:pk>/delete',
    #     views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

django_projects/batch/unesco/models.py
from django.db import models

class Category(models.Model) :
    name = models.CharField(max_length=128)

    def __str__(self) :
        return self.name


class States(models.Model) :
    name = models.CharField(max_length=128)

    def __str__(self) :
        return self.name

class Region(models.Model) :
    name = models.CharField(max_length=200)

    def __str__(self) :
        return self.name

class Iso(models.Model) :
    name = models.CharField(max_length=128)

    def __str__(self) :
        return self.name

class Site(models.Model):
    name = models.CharField(max_length=128)
    description = models.CharField(max_length=200, null=True)
    justification = models.CharField(max_length=200, null = True)
    year = models.IntegerField(null=True)
    longitude = models.FloatField(null=True)
    latitude = models.FloatField(null=True)
    area_hectares = models.FloatField(null=True)

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    states = models.ForeignKey(States, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    iso = models.ForeignKey(Iso, on_delete=models.CASCADE)
    def __str__(self) :
        return self.name

django_projects/batch/unesco/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponse

from unesco.models import Category, States, Region, Iso, Site


class RegionView(LoginRequiredMixin, View):
    def get(self, request):
        rg = Region.objects.all()[:10]
        # print("The sites are = {}".format(sl))

        ctx = {'region_list': rg}
        print("The region list = {}".format(ctx))
        return render(request, 'unesco/region_list.html', ctx)

class SiteDetailView(LoginRequiredMixin, View):
    def get(self,request,region_id):
        x = Site.objects.filter(region = region_id )[:10]
        ctx = {'site_list': x}
        print("ctx = {}".format(ctx))
        return render(request, 'unesco/site_list.html', ctx)

django_projects/batch/unesco/templates/unesco/all_sites.html
{% extends "base_bootstrap.html" %}

{% block content %}
 <h1>Site List</h1>
  {% if site_list %}
  <ul>
    {% for site in site_list %}
    <li>
      {{ site.name }} | {{site.year}}
      <a href="{% url 'unesco:regionsel_list' site.id %}">Region</a>
    </li>
    {% endfor %}
  </ul>
  {% endif %}

{% endblock %}

django_projects/batch/unesco/templates/unesco/region_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
 <h1>Region List</h1>
  {% if region_list %}
  <ul>
    {% for region in region_list %}
    <li>
      {{ region.name }}
      <a href="{% url 'unesco:site_list' region.id %}">Site</a>
    </li>
    {% endfor %}
  </ul>
  {% endif %}

{% endblock %}

django_projects/batch/unesco/templates/unesco/regionsel_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
 <h1>Region List</h1>
  {% if region_list %}
  <ul>
    {% for region in region_list %}
    <li>
      {{ site.name }} | {{site.year}}
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <a href="{% url 'unesco:all' %}">Back</a>
{% endblock %}

django_projects/batch/unesco/templates/unesco/site_detail.html
{% extends "base_bootstrap.html" %}

{% block content %}
 <h1>Site List</h1>
  <!-- {% if site_ %}
  <ul>
    {% for site in site_list %}
    <li>
      {{ site.name }} {{site.year}}
    </li>
    {% endfor %}
  </ul>
  {% endif %} -->

{% endblock %}

django_projects/batch/unesco/templates/unesco/site_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
 <h1>Site List</h1>
  {% if site_list %}
  <ul>
    {% for site in site_list %}
    <li>
      {{ site.name }} | {{site.year}}
    </li>
    {% endfor %}
  </ul>
  {% endif %}
  <a href="{% url 'unesco:all' %}">Back</a>
{% endblock %}

django_projects/batch/unesco/templates/unesco/unesco_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Unesco Site List</h1>
  {% if site_list %}
  <ul>
    {% for site in site_list %}
      <li>
          {{ site.name }} ({{ site.year }})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no sites in the library.</p>
  {% endif %}

 <h1>Region List</h1>
  {% if region_list %}
  <ul>
    {% for region in region_list %}
    <li>
      {{ region.name }}
    </li>
    {% endfor %}
  </ul>
  {% endif %}

{% endblock %}